myus/app/urls.py
from django.urls import path
from app.views import pjax, login_form, logout_form, signup_form, SignupComplete
from app.views import PasswordReset, PasswordResetDone, PasswordResetConfirm, PasswordResetComplete
from app.views import Index, Recommend, UserPage, UserPageInfo, UserPageAdvertise
from app.views import ProfileView, ProfileUpdate, MyPageView, MyPageUpdate, mypage_toggle, Withdrawal
from app.views import Payment, PaymentSuccess, PaymentCancel, ChangePlan, create_checkout_session
from app.views import UserNotificationView, notification_update, notification_confirmed, notification_deleted
from app.views import UserPolicy, Knowledge, FollowerList, FollowList, follow_create
from app.views import VideoList, VideoCreate, VideoDetail
from app.views import MusicList, MusicCreate, MusicDetail
from app.views import ComicList, ComicCreate, ComicDetail
from app.views import PictureList, PictureCreate, PictureDetail
from app.views import BlogList, BlogCreate, BlogDetail
from app.views import ChatList, ChatCreate, ChatDetail, ChatThread, chat_thread_button
from app.views import searchtag_create, advertise_read, like_form, like_form_comment
from app.views import comment_form, comment_update, comment_delete, reply_form, reply_delete

app_name = "app"

urlpatterns = [
    path("pjax", pjax, name="pjax"),
    path("login", login_form, name="login"),
    path("logout", logout_form, name="logout"),
    path("signup", signup_form, name="signup"),
    path("signup/complete/<token>/", SignupComplete.as_view(), name="signup_complete"),

    path("password_reset/", PasswordReset.as_view(), name="password_reset"),
    path("password_reset/done/", PasswordResetDone.as_view(), name="password_reset_done"),
    path("reset/<uidb64>/<token>/", PasswordResetConfirm.as_view(), name="password_reset_confirm"),
    path("reset/done/", PasswordResetComplete.as_view(), name="password_reset_complete"),

    path("", Index.as_view(), name="index"),
    path("recommend", Recommend.as_view(), name="recommend"),
    path("userpage/post/<str:nickname>", UserPage.as_view(), name="userpage"),
    path("userpage/information/<str:nickname>", UserPageInfo.as_view(), name="userpage_info"),
    path("userpage/advertise/<str:nickname>", UserPageAdvertise.as_view(), name="userpage_advertise"),

    path("setting/profile", ProfileView.as_view(), name="profile"),
    path("setting/profile/update", ProfileUpdate.as_view(), name="profile_update"),
    path("setting/mypage", MyPageView.as_view(), name="mypage"),
    path("setting/mypage/update", MyPageUpdate.as_view(), name="mypage_update"),
    path("setting/mypage/toggle", mypage_toggle, name="mypage_toggle"),
    path("setting/withdrawal", Withdrawal.as_view(), name="withdrawal"),
    path("setting/withdrawal/<str:token>", Withdrawal.as_view(), name="withdrawal"),

    path("setting/payment", Payment.as_view(), name="payment"),
    path("setting/payment/success", PaymentSuccess.as_view(), name="payment_success"),
    path("setting/payment/cancel", PaymentCancel.as_view(), name="payment_cancel"),
    path("setting/payment/chage_plan", ChangePlan.as_view(), name="chage_plan"),
    path("setting/payment/create_checkout_session", create_checkout_session, name="create_checkout_session"),

    path("setting/notification", UserNotificationView.as_view(), name="notification"),
    path("setting/notification/update", notification_update, name="notification_update"),
    path("setting/notification/confirmed", notification_confirmed, name="notification_confirmed"),
    path("setting/notification/deleted", notification_deleted, name="notification_deleted"),

    path("menu/userpolicy", UserPolicy.as_view(), name="userpolicy"),
    path("menu/knowledge", Knowledge.as_view(), name="knowledge"),
    path("menu/follower", FollowerList.as_view(), name="follower_list"),
    path("menu/follow", FollowList.as_view(), name="follow_list"),
    path("menu/follow/create/<str:nickname>", follow_create, name="follow_create"),

    path("media/video", VideoList.as_view(), name="video_list"),
    path("media/video/create", VideoCreate.as_view(), name="video_create"),
    path("media/video/detail/<int:pk>/<str:title>", VideoDetail.as_view(), name="video_detail"),

    path("media/music", MusicList.as_view(), name="music_list"),
    path("media/music/create", MusicCreate.as_view(), name="music_create"),
    path("media/music/detail/<int:pk>/<str:title>", MusicDetail.as_view(), name="music_detail"),

    path("media/comic", ComicList.as_view(), name="comic_list"),
    path("media/comic/create", ComicCreate.as_view(), name="comic_create"),
    path("media/comic/detail/<int:pk>/<str:title>", ComicDetail.as_view(), name="comic_detail"),

    path("media/picture", PictureList.as_view(), name="picture_list"),
    path("media/picture/create", PictureCreate.as_view(), name="picture_create"),
    path("media/picture/detail/<int:pk>/<str:title>", PictureDetail.as_view(), name="picture_detail"),

    path("media/blog", BlogList.as_view(), name="blog_list"),
    path("media/blog/create", BlogCreate.as_view(), name="blog_create"),
    path("media/blog/detail/<int:pk>/<str:title>", BlogDetail.as_view(), name="blog_detail"),

    path("media/chat", ChatList.as_view(), name="chat_list"),
    path("media/chat/create", ChatCreate.as_view(), name="chat_create"),
    path("media/chat/detail/<int:pk>", ChatDetail.as_view(), name="chat_detail"),
    path("media/chat/detail/<int:pk>/thread/<int:message_id>", ChatThread.as_view(), name="chat_thread"),
    path("media/chat/detail/thread", chat_thread_button, name="chat_thread_button"),

    path("searchtag/create", searchtag_create, name="searchtag_create"),
    path("url/read", advertise_read, name="advertise_read"),
    path("like/form", like_form, name="like_form"),
    path("like/form/comment", like_form_comment, name="like_form_comment"),

    path("comment/form", comment_form, name="comment_form"),
    path("comment/update/<int:comment_id>", comment_update, name="comment_update"),
    path("comment/delete/<int:comment_id>", comment_delete, name="comment_delete"),
    path("reply/form", reply_form, name="reply_form"),
    path("reply/delete/<int:comment_id>", reply_delete, name="reply_delete"),
]

myus/api/db/models/common.py
from django.db import models
from django_ulid.models import ulid
from api.db.models.user import User


class AccessLog(models.Model):
    """AccessLog"""
    id         = models.BigAutoField(primary_key=True)
    ip_address = models.GenericIPAddressField()
    type       = models.CharField(max_length=7)
    type_id    = models.BigIntegerField()
    created    = models.DateTimeField(auto_now_add=True)
    updated    = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.ip_address)

    class Meta:
        db_table = "access_log"
        verbose_name_plural = "002 Access Log"
        indexes = [models.Index(fields=["ip_address", "type", "type_id"], name="ip_address_type_idx")]


class Advertise(models.Model):
    """Advertise"""
    choice  = (("all", "全体"), ("one", "個別"))
    id      = models.BigAutoField(primary_key=True)
    ulid    = models.CharField(max_length=26, unique=True, editable=False, default=ulid.new)
    author  = models.ForeignKey(User, on_delete=models.CASCADE)
    title   = models.CharField(max_length=100)
    url     = models.URLField()
    content = models.TextField()
    image   = models.ImageField(blank=True)
    video   = models.FileField(blank=True)
    read    = models.IntegerField(default=0)
    type    = models.CharField(choices=choice, max_length=3)
    period  = models.DateField()
    publish = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        db_table = "advertise"
        verbose_name_plural = "12 広告設定"

myus/api/models/common.py
from django.db import models
from django_ulid.models import ulid
from api.models.user import User
from api.utils.functions.file import image_upload, video_upload


class AccessLog(models.Model):
    """AccessLog"""
    id         = models.BigAutoField(primary_key=True)
    ip_address = models.GenericIPAddressField()
    type       = models.CharField(max_length=7, blank=True)
    type_id    = models.BigIntegerField(blank=True, null=True)
    created    = models.DateTimeField(auto_now_add=True)
    updated    = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.ip_address)

    class Meta:
        db_table = "access_log"
        verbose_name_plural = "002 Access Log"
        indexes = [models.Index(fields=["ip_address", "type", "type_id"], name="ip_address_type_idx")]


class Advertise(models.Model):
    """Advertise"""
    choice  = (("all", "全体"), ("one", "個別"))
    id      = models.BigAutoField(primary_key=True)
    ulid    = models.CharField(max_length=26, unique=True, editable=False, default=ulid.new)
    author  = models.ForeignKey(User, on_delete=models.CASCADE)
    title   = models.CharField(max_length=100)
    url     = models.URLField()
    content = models.TextField()
    image   = models.ImageField(upload_to=image_upload)
    video   = models.FileField(upload_to=video_upload)
    read    = models.IntegerField(default=0)
    type    = models.CharField(choices=choice, max_length=3)
    period  = models.DateField()
    publish = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if self.id is None:
            image = self.image
            video  = self.video
            self.image = None
            self.video  = None
            super().save(*args, **kwargs)
            self.image = image
            self.video  = video
            if "force_insert" in kwargs:
                kwargs.pop("force_insert")
        super().save(*args, **kwargs)

    class Meta:
        db_table = "advertise"
        verbose_name_plural = "12 広告設定"

myus/templates/parts/common/common.html
{% load static %}
{% load humanize %}

<div class="media_detail_aria">
  <h1 title="{{ object.title }}">{{ object.title }}</h1>

  <time class="media_detail_aria_1">{{ object.created|date:'Y/m/d H:i' }}</time>

  <div class="media_detail_aria_2">
    <div class="read">
      <i class="bi bi-caret-right-square icon_font" title="閲覧数"></i>
      <span>{{ object.read|intcomma }}</span>
    </div>
    {% if user.is_authenticated %}
    <form method="POST" action="" obj-id="{{ object.id }}" path="{{ request.path }}" csrf="{{ csrf_token }}">
      {% if is_like %}
      <button type="submit" name="like" class="like_form like_fill">
        <i class="bi bi-hand-thumbs-up-fill icon_font like_color" title="いいね"></i>
      </button>
      {% else %}
      <button type="submit" name="like" class="like_form like_no">
        <i class="bi bi-hand-thumbs-up icon_font like_color" title="いいね"></i>
      </button>
      {% endif %}
      <span id="like_count_object_{{ object.id }}" class="like_count">{{ object.total_like|intcomma }}</span>
    </form>
    {% else %}
    <i class="bi bi-hand-thumbs-up icon_font" title="いいね"></i>
    <span>{{ object.total_like|intcomma }}</span>
    {% endif %}
  </div>

  <div class="media_detail_aria_3">
    {% include 'parts/common/hashtag.html' %}
  </div>
</div>
<hr>

<input type="checkbox" id="content_detail_check_id" class="content_detail_check">
<label for="content_detail_check_id" class="content_detail_label1">拡大表示</label>
<label for="content_detail_check_id" class="content_detail_label2">縮小表示</label>

<div class="content_detail_aria">
  <div class="content_detail">
    <a href="{% url 'app:userpage' object.author.nickname %}" data="{{ object.author.nickname }}" class="pjax_button_userpage">
      <img src="{{ object.author.image }}" title="{{ object.author.nickname }}" class="profile_image_detail">
    </a>
    <div class="username_space">{{ object.author.nickname }}</div>
    <div class="registered_person">登録者数
      <span class="follower_count">{{ object.author.mypage.follower_count }}</span>
    </div>
    <p class="content_detail_p1">{{ object.content|linebreaksbr|urlize }}</p>

    <div class="content_detail_p2">
      {% if user.nickname == object.author.nickname %}
      <button class="button green" disabled>フォローする</button>
      {% elif user.is_authenticated %}
      <form method="POST" action="" value="{{ object.author.nickname }}" csrf="{{ csrf_token }}" class="follow_form">
        {% if is_follow %}
        <button type="button" name="following_id" class="button red follow_change">解除する</button>
        {% else %}
        <button type="button" name="following_id" class="button green follow_change">フォローする</button>
        {% endif %}
      </form>
      {% else %}
      <button class="button green" disabled>フォローする</button>
      {% endif %}
    </div>
  </div>
</div>
<hr>

{% include 'parts/common/comment/comment_create.html' %}

<input type="checkbox" id="comment_aria_check_id" class="comment_aria_check">
<label for="comment_aria_check_id" class="comment_aria_check_label1">拡大表示</label>
<label for="comment_aria_check_id" class="comment_aria_check_label2">縮小表示</label>

<div id="comment_aria" class="comment_aria">
  {% include 'parts/common/comment/comment.html' %}
</div>

<hr class="comment_aria_hr">

<div class="advertise_aria">
  <h2>広告表示</h2>
  <article class="article_list">
    {% include 'parts/advertise_article_auto.html' %}
  </article>
  <hr>

  <h2>個別広告</h2>
  <article class="article_list">
    {% include 'parts/advertise_article.html' %}
  </article>
</div>

myus/templates/parts/common/hashtag.html
{% for hashtag in object.hashtag.all %}
  <div class="hashtag_list">
    <a href="/?search={{ hashtag.jp_name }}" search={{ hashtag.jp_name }} class="pjax_hash_search">#{{ hashtag.jp_name }}</a>
  </div>
{% endfor %}