myus/app/urls.py
from django.urls import path
from app.views import pjax, login_form, logout_form, signup_form, SignupComplete
from app.views import PasswordReset, PasswordResetDone, PasswordResetConfirm, PasswordResetComplete
from app.views import Index, Recommend, UserPage, UserPageInfo, UserPageAdvertise
from app.views import ProfileView, ProfileUpdate, MyPageView, MyPageUpdate, mypage_toggle, Withdrawal
from app.views import Payment, PaymentSuccess, PaymentCancel, ChangePlan, create_checkout_session
from app.views import UserNotificationView, notification_update, notification_confirmed, notification_deleted
from app.views import UserPolicy, Knowledge, FollowerList, FollowList, follow_create
from app.views import VideoList, VideoCreate, VideoDetail
from app.views import MusicList, MusicCreate, MusicDetail
from app.views import ComicList, ComicCreate, ComicDetail
from app.views import PictureList, PictureCreate, PictureDetail
from app.views import BlogList, BlogCreate, BlogDetail
from app.views import ChatList, ChatCreate, ChatDetail, ChatThread, chat_thread_button
from app.views import searchtag_create, advertise_read, like_form, like_form_comment
from app.views import comment_form, comment_update, comment_delete, reply_form, reply_delete

app_name = "app"

urlpatterns = [
    path("pjax", pjax, name="pjax"),
    path("login", login_form, name="login"),
    path("logout", logout_form, name="logout"),
    path("signup", signup_form, name="signup"),
    path("signup/complete/<token>/", SignupComplete.as_view(), name="signup_complete"),

    path("password_reset/", PasswordReset.as_view(), name="password_reset"),
    path("password_reset/done/", PasswordResetDone.as_view(), name="password_reset_done"),
    path("reset/<uidb64>/<token>/", PasswordResetConfirm.as_view(), name="password_reset_confirm"),
    path("reset/done/", PasswordResetComplete.as_view(), name="password_reset_complete"),

    path("", Index.as_view(), name="index"),
    path("recommend", Recommend.as_view(), name="recommend"),
    path("userpage/post/<str:nickname>", UserPage.as_view(), name="userpage"),
    path("userpage/information/<str:nickname>", UserPageInfo.as_view(), name="userpage_info"),
    path("userpage/advertise/<str:nickname>", UserPageAdvertise.as_view(), name="userpage_advertise"),

    path("setting/profile", ProfileView.as_view(), name="profile"),
    path("setting/profile/update", ProfileUpdate.as_view(), name="profile_update"),
    path("setting/mypage", MyPageView.as_view(), name="mypage"),
    path("setting/mypage/update", MyPageUpdate.as_view(), name="mypage_update"),
    path("setting/mypage/toggle", mypage_toggle, name="mypage_toggle"),
    path("setting/withdrawal", Withdrawal.as_view(), name="withdrawal"),
    path("setting/withdrawal/<str:token>", Withdrawal.as_view(), name="withdrawal"),

    path("setting/payment", Payment.as_view(), name="payment"),
    path("setting/payment/success", PaymentSuccess.as_view(), name="payment_success"),
    path("setting/payment/cancel", PaymentCancel.as_view(), name="payment_cancel"),
    path("setting/payment/chage_plan", ChangePlan.as_view(), name="chage_plan"),
    path("setting/payment/create_checkout_session", create_checkout_session, name="create_checkout_session"),

    path("setting/notification", UserNotificationView.as_view(), name="notification"),
    path("setting/notification/update", notification_update, name="notification_update"),
    path("setting/notification/confirmed", notification_confirmed, name="notification_confirmed"),
    path("setting/notification/deleted", notification_deleted, name="notification_deleted"),

    path("menu/userpolicy", UserPolicy.as_view(), name="userpolicy"),
    path("menu/knowledge", Knowledge.as_view(), name="knowledge"),
    path("menu/follower", FollowerList.as_view(), name="follower_list"),
    path("menu/follow", FollowList.as_view(), name="follow_list"),
    path("menu/follow/create/<str:nickname>", follow_create, name="follow_create"),

    path("media/video", VideoList.as_view(), name="video_list"),
    path("media/video/create", VideoCreate.as_view(), name="video_create"),
    path("media/video/detail/<int:pk>/<str:title>", VideoDetail.as_view(), name="video_detail"),

    path("media/music", MusicList.as_view(), name="music_list"),
    path("media/music/create", MusicCreate.as_view(), name="music_create"),
    path("media/music/detail/<int:pk>/<str:title>", MusicDetail.as_view(), name="music_detail"),

    path("media/comic", ComicList.as_view(), name="comic_list"),
    path("media/comic/create", ComicCreate.as_view(), name="comic_create"),
    path("media/comic/detail/<int:pk>/<str:title>", ComicDetail.as_view(), name="comic_detail"),

    path("media/picture", PictureList.as_view(), name="picture_list"),
    path("media/picture/create", PictureCreate.as_view(), name="picture_create"),
    path("media/picture/detail/<int:pk>/<str:title>", PictureDetail.as_view(), name="picture_detail"),

    path("media/blog", BlogList.as_view(), name="blog_list"),
    path("media/blog/create", BlogCreate.as_view(), name="blog_create"),
    path("media/blog/detail/<int:pk>/<str:title>", BlogDetail.as_view(), name="blog_detail"),

    path("media/chat", ChatList.as_view(), name="chat_list"),
    path("media/chat/create", ChatCreate.as_view(), name="chat_create"),
    path("media/chat/detail/<int:pk>", ChatDetail.as_view(), name="chat_detail"),
    path("media/chat/detail/<int:pk>/thread/<int:message_id>", ChatThread.as_view(), name="chat_thread"),
    path("media/chat/detail/thread", chat_thread_button, name="chat_thread_button"),

    path("searchtag/create", searchtag_create, name="searchtag_create"),
    path("url/read", advertise_read, name="advertise_read"),
    path("like/form", like_form, name="like_form"),
    path("like/form/comment", like_form_comment, name="like_form_comment"),

    path("comment/form", comment_form, name="comment_form"),
    path("comment/update/<int:comment_id>", comment_update, name="comment_update"),
    path("comment/delete/<int:comment_id>", comment_delete, name="comment_delete"),
    path("reply/form", reply_form, name="reply_form"),
    path("reply/delete/<int:comment_id>", reply_delete, name="reply_delete"),
]

myus/api/db/models/media.py
from django.db import models
from django_quill.fields import QuillField
from django_ulid.models import ulid
from api.db.models.base import MediaModel
from api.db.models.channel import Channel
from api.db.models.master import Category, HashTag
from api.db.models.user import User
from api.utils.functions.file import comic_upload, image_upload, music_upload, video_upload


# Video
class Video(models.Model, MediaModel):
    """Video"""
    id       = models.BigAutoField(primary_key=True)
    ulid     = models.CharField(max_length=26, unique=True, editable=False, default=ulid.new)
    channel  = models.ForeignKey(Channel, on_delete=models.CASCADE, related_name="videos")
    title    = models.CharField(max_length=100)
    content  = models.TextField()
    image    = models.ImageField(upload_to=image_upload, blank=True)
    video    = models.FileField(upload_to=video_upload, blank=True)
    convert  = models.FileField(upload_to=video_upload, blank=True)
    category = models.ManyToManyField(Category, blank=True)
    hashtag  = models.ManyToManyField(HashTag, blank=True)
    like     = models.ManyToManyField(User, related_name="video_like", blank=True)
    read     = models.IntegerField(default=0)
    publish  = models.BooleanField(default=True)
    created  = models.DateTimeField(auto_now_add=True)
    updated  = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "video"
        verbose_name_plural = "01 Video"


# Music
class Music(models.Model, MediaModel):
    """Music"""
    id       = models.BigAutoField(primary_key=True)
    ulid     = models.CharField(max_length=26, unique=True, editable=False, default=ulid.new)
    channel  = models.ForeignKey(Channel, on_delete=models.CASCADE, related_name="musics")
    title    = models.CharField(max_length=100)
    content  = models.TextField()
    lyric    = models.TextField()
    music    = models.FileField(upload_to=music_upload, blank=True)
    category = models.ManyToManyField(Category, blank=True)
    hashtag  = models.ManyToManyField(HashTag, blank=True)
    like     = models.ManyToManyField(User, related_name="music_like", blank=True)
    read     = models.IntegerField(default=0)
    download = models.BooleanField(default=True)
    publish  = models.BooleanField(default=True)
    created  = models.DateTimeField(auto_now_add=True)
    updated  = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "music"
        verbose_name_plural = "02 Music"


# Comic
class Comic(models.Model, MediaModel):
    """Comic"""
    id       = models.BigAutoField(primary_key=True)
    ulid     = models.CharField(max_length=26, unique=True, editable=False, default=ulid.new)
    channel  = models.ForeignKey(Channel, on_delete=models.CASCADE, related_name="comics")
    title    = models.CharField(max_length=100)
    content  = models.TextField()
    image    = models.ImageField(upload_to=image_upload, blank=True)
    category = models.ManyToManyField(Category, blank=True)
    hashtag  = models.ManyToManyField(HashTag, blank=True)
    like     = models.ManyToManyField(User, related_name="comic_like", blank=True)
    read     = models.IntegerField(default=0)
    publish  = models.BooleanField(default=True)
    created  = models.DateTimeField(auto_now_add=True)
    updated  = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "comic"
        verbose_name_plural = "03 Comic"


class ComicPage(models.Model):
    """ComicPage"""
    id    = models.BigAutoField(primary_key=True)
    comic = models.ForeignKey(Comic, on_delete=models.CASCADE, related_name="comic")
    image = models.ImageField(upload_to=comic_upload, blank=True)
    sequence = models.IntegerField(default=0)

    class Meta:
        db_table = "comic_page"
        verbose_name_plural = "03 ComicPage"
        constraints = [
            models.UniqueConstraint(fields=["comic", "sequence"], name="lesson_unique")
        ]

# Picture
class Picture(models.Model, MediaModel):
    """Picture"""
    id       = models.BigAutoField(primary_key=True)
    ulid     = models.CharField(max_length=26, unique=True, editable=False, default=ulid.new)
    channel  = models.ForeignKey(Channel, on_delete=models.CASCADE, related_name="pictures")
    title    = models.CharField(max_length=100)
    content  = models.TextField()
    image    = models.ImageField(upload_to=image_upload, blank=True)
    category = models.ManyToManyField(Category, blank=True)
    hashtag  = models.ManyToManyField(HashTag, blank=True)
    like     = models.ManyToManyField(User, related_name="picture_like", blank=True)
    read     = models.IntegerField(default=0)
    publish  = models.BooleanField(default=True)
    created  = models.DateTimeField(auto_now_add=True)
    updated  = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "picture"
        verbose_name_plural = "04 Picture"


# Blog
class Blog(models.Model, MediaModel):
    """Blog"""
    id       = models.BigAutoField(primary_key=True)
    ulid     = models.CharField(max_length=26, unique=True, editable=False, default=ulid.new)
    channel  = models.ForeignKey(Channel, on_delete=models.CASCADE, related_name="blogs")
    title    = models.CharField(max_length=100)
    content  = models.TextField()
    richtext = models.TextField()
    delta    = QuillField()
    image    = models.ImageField(upload_to=image_upload, blank=True)
    category = models.ManyToManyField(Category, blank=True)
    hashtag  = models.ManyToManyField(HashTag, blank=True)
    like     = models.ManyToManyField(User, related_name="blog_like", blank=True)
    read     = models.IntegerField(default=0)
    publish  = models.BooleanField(default=True)
    created  = models.DateTimeField(auto_now_add=True)
    updated  = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "blog"
        verbose_name_plural = "05 Blog"


# Chat
class Chat(models.Model):
    """Chat"""
    id       = models.BigAutoField(primary_key=True)
    ulid     = models.CharField(max_length=26, unique=True, editable=False, default=ulid.new)
    channel  = models.ForeignKey(Channel, on_delete=models.CASCADE, related_name="chats")
    title    = models.CharField(max_length=100)
    content  = models.TextField()
    category = models.ManyToManyField(Category, blank=True)
    hashtag  = models.ManyToManyField(HashTag, blank=True)
    like     = models.ManyToManyField(User, related_name="chat_like", blank=True)
    read     = models.IntegerField(default=0)
    period   = models.DateField()
    publish  = models.BooleanField(default=True)
    created  = models.DateTimeField(auto_now_add=True)
    updated  = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def total_like(self):
        return self.like.count()
    total_like.short_description = "like"

    def thread_count(self) -> int:
        return self.message.filter(parent__isnull=True).count()
    thread_count.short_description = "thread"

    def joined_count(self) -> int:
        return self.message.values_list("author").distinct().count()
    joined_count.short_description = "joined"

    def score(self):
        return int(self.read + self.like.count()*10 + self.read*self.like.count()/(self.read+1)*20)

    class Meta:
        db_table = "chat"
        verbose_name_plural = "06 Chat"

myus/templates/media/video/video.html
{% extends 'base2.html' %}
{% block title %}<title>MyUsビデオ</title>{% endblock title %}

{% block content %}
<main class="main">
  {% include 'media/video/video_list.html' %}
</main>
{% endblock content %}

myus/templates/media/video/video_article.html
{% load static %}

<section class="section_list">
  <div class="main_decolation">
    <a href="{% url 'app:video_detail' item.pk item.title %}">
      <div class="video video_auto">
        <video class="video-js vjs-16-9" muted width="272" height="153" controlsList="nodownload" oncontextmenu="return false;" poster="{{ item.image.url }}" data-setup="">
          <source src="{{ item.convert.url }}#t=,16" type="video/mp4" label="360p" res="360">
          <p>動画を再生するには、videoタグをサポートしたブラウザが必要です!</p>
          <track kind="captions" src="{% static 'vtt/captions.ja.vtt' %}" srclang="en" label="English">
          <track kind="subtitles" src="{% static 'vtt/captions.ja.vtt' %}" srclang="en" label="English">
        </video>
        <div class="author_space">
          {% include 'parts/author_space.html' %}
          {% include 'parts/content_title.html' %}
        </div>
      </div>
    </a>
  </div>
</section>

myus/templates/media/video/video_article_detail.html
{% load static %}

{% for item in video_list %}
<section class="section_detail">
  <div class="main_decolation">
    <div class="video video_auto">
      <a href="{% url 'app:video_detail' item.pk item.title %}" class="content_side">
        <video class="video-js" muted width="192" height="108" controlsList="nodownload" oncontextmenu="return false;" poster="{{ item.image.url }}" data-setup="">
          <source src="{{ item.convert.url }}#t=,16" type="video/mp4" label="360p" res="360">
          <p>動画を再生するには、videoタグをサポートしたブラウザが必要です!</p>
          <track kind="captions" src="{% static 'vtt/captions.ja.vtt' %}" srclang="en" label="English">
          <track kind="subtitles" src="{% static 'vtt/captions.ja.vtt' %}" srclang="en" label="English">
        </video>
        <div class="author_space_side">
          {% include 'parts/content_title.html' %}
        </div>
      </a>
    </div>
  </div>
</section>
{% endfor %}

myus/templates/media/video/video_create.html
{% extends 'base2.html' %}
{% block title %}<title>MyUsビデオ</title>{% endblock title %}

{% block content %}
<main class="main">
  {% include 'media/video/video_create_content.html' %}
</main>
{% endblock content %}

myus/templates/media/video/video_create_content.html
{% load static %}

<div class="main_header">
  <h1>Video</h1>
  {% if user.is_authenticated %}
  <div className="main_button_area">
    <button type="submit" class="button green s">作成する</button>
  </div>
  {% endif %}
</div>

{% if user.is_authenticated %}
<article class="mv_24">
  <form method="POST" action="" enctype="multipart/form-data" class="create_grid">
    {% csrf_token %}
    <div>
      <p class="mb_4">タイトル</p>
      <input name="title" class="input" required>
    </div>


    <div>
      <p class="mb_4">内容</p>
      <textarea name="content" rows="1" class="textarea" required></textarea>
    </div>

    <div>
      <p class="mb_4">サムネイル</p>
      <input type="file" name="image" accept="image/*" class="input file_1" hidden required>
      <input placeholder="ファイル選択..." id="file_1" class="input" onclick="$('input.file_1').click()">
    </div>

    <div>
      <p class="mb_4">動画</p>
      <input type="file" name="convert" accept="video/*" class="input file_2" hidden required>
      <input placeholder="ファイル選択..." id="file_2" class="input" onclick="$('input.file_2').click()">
    </div>
  </form>
</article>
{% else %}
<h2 class="login_required">ログインしてください</h2>
{% endif %}

{% block extrajs %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="{% static 'js/textarea.js' %}"></script>
<script src="{% static 'js/filename.js' %}"></script>
{% endblock extrajs %}

myus/templates/media/video/video_detail.html
{% extends 'base2.html' %}
{% block title %}<title>MyUsビデオ</title>{% endblock title %}
{% load static %}
{% load humanize %}

{% include 'parts/google_tag_user.html' %}

{% block content %}
<main class="main">
  <article class="media_detail">
  {% if object.publish %}
    <div class="media_detail_video">
      <div class="media_detail_contents">
        <video-js id="video" class="video-js vjs-fluid vjs-big-play-centered vjs-16-9" controls controlsList="nodownload" oncontextmenu="return false;" poster="{{ object.image.url }}" data-setup='{"playbackRates": [0.5, 1, 1.25, 1.5, 2]}'>
          <source src="{{ object.video.url }}" type="application/x-mpegURL">
          <p>動画を再生するには、videoタグをサポートしたブラウザが必要です!</p>
          <track kind="captions" src="{% static 'vtt/captions.ja.vtt' %}" srclang="en" label="English">
          <track kind="subtitles" src="{% static 'vtt/captions.ja.vtt' %}" srclang="en" label="English">
          <p class="vjs-no-js">この動画を見るには、JavaScriptを有効にしてください!
            <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
          </p>
        </video-js>
      </div>
    </div>

    <div class="media_detail_grid">
      <div class="media_detail_grid_1">
        {% include 'parts/common/common.html' %}
      </div>
      <div class="media_detail_grid_2">
        {% include 'media/video/video_article_detail.html' %}
      </div>
    </div>
  {% else %}
  <h2 class="unpublished">非公開に設定されてます!</h2>
  {% endif %}
  </article>
</main>
{% endblock content %}

{% block extrajs %}
<script src="{% static 'js/ajax_comment.js' %}"></script>
{% endblock extrajs %}

myus/templates/media/video/video_list.html
{% load static %}

<h1>Video</h1>
{% if query %}
<section class="main_search_message">「{{ query }}」の検索結果「{{ count }}」件</section>
{% endif %}

<article class="article_list">
{% for item in video_list %}
  {% include 'media/video/video_article.html' %}
{% endfor %}
</article>

{% block extrajs %}
<script src="https://vjs.zencdn.net/7.19.2/video.min.js"></script>
<script src="{% static 'js/video_auto.js' %}"></script>
{% endblock extrajs %}