api/urls.py
from django.urls import path
from api.views import Index, Recommend, UserPage, UserPageInfo, UserPageAdvertise
from api.views import Profile, ProfileUpdate, MyPageView, MyPageUpdate, mypage_toggle
from api.views import Payment, PaymentSuccess, PaymentCancel, ChangePlan, create_checkout_session
from api.views import NotificationSettingView, notification_setting, notification_confirmed, notification_deleted
from api.views import UserPolicy, Knowledge, FollowerList, FollowList, follow_create
from api.views import VideoList, VideoCreate, VideoDetail
from api.views import LiveList, LiveCreate, LiveDetail
from api.views import MusicList, MusicCreate, MusicDetail
from api.views import PictureList, PictureCreate, PictureDetail
from api.views import BlogList, BlogCreate, BlogDetail
from api.views import ChatList, ChatCreate, ChatDetail, ChatThread, chat_thread_button
from api.views import CollaboList, CollaboCreate, CollaboDetail
from api.views import TodoList, TodoDetail, TodoCreate, TodoDelete, TodoUpdate
from api.views import searchtag_create, advertise_read, like_form, like_form_comment
from api.views import comment_form, reply_form, comment_update, comment_delete, reply_delete
from api.views import pjax, signup_form, login_form, logout_form, Withdrawal

app_name = 'myus'

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('recommend', Recommend.as_view(), name='recommend'),
    path('userpage/post/<str:nickname>', UserPage.as_view(), name='userpage'),
    path('userpage/information/<str:nickname>', UserPageInfo.as_view(), name='userpage_info'),
    path('userpage/advertise/<str:nickname>', UserPageAdvertise.as_view(), name='userpage_advertise'),

    path('profile', Profile.as_view(), name='profile'),
    path('profile/update', ProfileUpdate.as_view(), name='profile_update'),
    path('mypage', MyPageView.as_view(), name='mypage'),
    path('mypage/update', MyPageUpdate.as_view(), name='mypage_update'),
    path('mypage/toggle', mypage_toggle, name='mypage_toggle'),

    path('payment', Payment.as_view(), name='payment'),
    path('payment/success', PaymentSuccess.as_view(), name='payment_success'),
    path('payment/cancel', PaymentCancel.as_view(), name='payment_cancel'),
    path('payment/chage_plan', ChangePlan.as_view(), name='chage_plan'),
    path('payment/create_checkout_session', create_checkout_session, name='create_checkout_session'),

    path('notification', NotificationSettingView.as_view(), name='notification'),
    path('notification/setting', notification_setting, name='notification_setting'),
    path('notification/confirmed', notification_confirmed, name='notification_confirmed'),
    path('notification/deleted', notification_deleted, name='notification_deleted'),

    path('userpolicy', UserPolicy.as_view(), name='userpolicy'),
    path('knowledge', Knowledge.as_view(), name='knowledge'),
    path('follower', FollowerList.as_view(), name='follower_list'),
    path('follow', FollowList.as_view(), name='follow_list'),
    path('follow/create/<str:nickname>', follow_create, name='follow_create'),

    path('video', VideoList.as_view(), name='video_list'),
    path('video/create', VideoCreate.as_view(), name='video_create'),
    path('video/detail/<int:pk>/<str:title>', VideoDetail.as_view(), name='video_detail'),

    path('live', LiveList.as_view(), name='live_list'),
    path('live/create', LiveCreate.as_view(), name='live_create'),
    path('live/detail/<int:pk>/<str:title>', LiveDetail.as_view(), name='live_detail'),

    path('music', MusicList.as_view(), name='music_list'),
    path('music/create', MusicCreate.as_view(), name='music_create'),
    path('music/detail/<int:pk>/<str:title>', MusicDetail.as_view(), name='music_detail'),

    path('picture', PictureList.as_view(), name='picture_list'),
    path('picture/create', PictureCreate.as_view(), name='picture_create'),
    path('picture/detail/<int:pk>/<str:title>', PictureDetail.as_view(), name='picture_detail'),

    path('blog', BlogList.as_view(), name='blog_list'),
    path('blog/create', BlogCreate.as_view(), name='blog_create'),
    path('blog/detail/<int:pk>/<str:title>', BlogDetail.as_view(), name='blog_detail'),

    path('chat', ChatList.as_view(), name='chat_list'),
    path('chat/create', ChatCreate.as_view(), name='chat_create'),
    path('chat/detail/<int:pk>', ChatDetail.as_view(), name='chat_detail'),
    path('chat/detail/<int:pk>/thread/<int:comment_id>', ChatThread.as_view(), name='chat_thread'),
    path('chat/detail/thread', chat_thread_button, name='chat_thread_button'),

    path('collabo', CollaboList.as_view(), name='collabo_list'),
    path('collabo/create', CollaboCreate.as_view(), name='collabo_create'),
    path('collabo/detail/<int:pk>/<str:title>', CollaboDetail.as_view(), name='collabo_detail'),

    path('todo', TodoList.as_view(), name='todo_list'),
    path('todo/create', TodoCreate.as_view(), name='todo_create'),
    path('todo/detail/<int:pk>/<str:title>', TodoDetail.as_view(), name='todo_detail'),
    path('todo/update/<int:pk>/<str:title>', TodoUpdate.as_view(), name='todo_update'),
    path('todo/delete/<int:pk>/<str:title>', TodoDelete.as_view(), name='todo_delete'),

    path('searchtag/create', searchtag_create, name='searchtag_create'),
    path('url/read', advertise_read, name='advertise_read'),
    path('like/form', like_form, name='like_form'),
    path('like/form/comment', like_form_comment, name='like_form_comment'),

    path('comment/form', comment_form, name='comment_form'),
    path('reply/form', reply_form, name='reply_form'),
    path('comment/update/<int:comment_id>', comment_update, name='comment_update'),
    path('comment/delete/<int:comment_id>', comment_delete, name='comment_delete'),
    path('reply/delete/<int:comment_id>', reply_delete, name='reply_delete'),

    path('pjax', pjax, name='pjax'),
    path('signup', signup_form, name='signup'),
    path('login', login_form, name='login'),
    path('logout', logout_form, name='logout'),
    path('withdrawal', Withdrawal.as_view(), name='withdrawal'),
    path('withdrawal/<str:token>', Withdrawal.as_view(), name='withdrawal'),
]

myus/api/db/models/comment.py
from django.db import models
from django_ulid.models import ulid
from api.db.models.user import User


class Comment(models.Model):
    """Comment"""
    id        = models.BigAutoField(primary_key=True)
    ulid      = models.CharField(max_length=26, unique=True, editable=False, default=ulid.new)
    author    = models.ForeignKey(User, on_delete=models.CASCADE)
    parent    = models.ForeignKey("self", on_delete=models.CASCADE, related_name="reply", null=True)
    type_no   = models.IntegerField()
    type_name = models.CharField(max_length=7)
    object_id = models.PositiveIntegerField()
    text      = models.TextField()
    like      = models.ManyToManyField(User, related_name="comment_like", blank=True)
    deleted   = models.BooleanField(default=False)
    created   = models.DateTimeField(auto_now_add=True)
    updated   = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.id)

    def total_like(self) -> int:
        return self.like.count()
    total_like.short_description = "like"

    def reply_count(self) -> int:
        return self.reply.filter(parent=self).count()
    reply_count.short_description = "reply"

    class Meta:
        db_table = "comment"
        verbose_name_plural = "13 コメント"
        indexes = [
            models.Index(fields=["parent"], name="comment_parent_idx"),
            models.Index(fields=["type_no", "object_id"], name="comment_type_object_idx"),
        ]

myus/api/models/comment.py
from django.db import models
from django.db.models import Count
from django_ulid.models import ulid
from api.models.user import User


class CommentManager(models.Manager):
    def get_queryset(self):
        qs = super(CommentManager,self).get_queryset().annotate(reply_count=Count("reply"))
        return qs.select_related("author", "parent").prefetch_related("like")


class Comment(models.Model):
    """Comment"""
    id        = models.BigAutoField(primary_key=True)
    ulid      = models.CharField(max_length=26, unique=True, editable=False, default=ulid.new)
    author    = models.ForeignKey(User, on_delete=models.CASCADE)
    parent    = models.ForeignKey("self", on_delete=models.CASCADE, related_name="reply", blank=True, null=True)
    type_no   = models.IntegerField()
    type_name = models.CharField(max_length=7, blank=True)
    object_id = models.PositiveIntegerField()
    text      = models.TextField()
    like      = models.ManyToManyField(User, related_name="comment_like", blank=True)
    deleted   = models.BooleanField(default=False)
    created   = models.DateTimeField(auto_now_add=True)
    updated   = models.DateTimeField(auto_now=True)

    objects = CommentManager()

    def __str__(self):
        return str(self.id)

    def total_like(self):
        return self.like.count()
    total_like.short_description = "like"

    def reply_count(self):
        return self.reply.filter(parent=self).count()
    reply_count.short_description = "reply"

    class Meta:
        db_table = "comment"
        verbose_name_plural = "13 コメント"
        indexes = [
            models.Index(fields=["parent"], name="comment_parent_idx"),
            models.Index(fields=["type_no", "object_id"], name="comment_type_object_idx"),
        ]

templates/parts/chat_section_thread.html
<div class="chat_section_header_cross">
    <h2>スレッド</h2>
    <a href="{% url 'myus:chat_detail' object.pk object.title %}">
        <i class="bi bi-x" style="font-size: 1.7em;" title="閉じる"></i>
    </a>
</div>

<div class="chat_section_thread">
    {% for comment in comment_list %}
        {% if comment.id == comment_id %}
        <div class="comment_aria_list">
            <a href="{% url 'myus:userpage' comment.author.nickname %}">
                <img src="{{ comment.author.user_image.url }}" title="{{ comment.author.nickname }}" class="profile_image_comment">
            </a>
            <div class="comment_aria_list_1">
                <p>{{ comment.author.nickname }}</p>
                <time>{{ comment.created|date:'Y/m/d H:i' }}</time>
            </div>
            <div class="comment_aria_list_2">{{ comment.text|linebreaksbr|urlize }}</div>
        </div>
        {% endif %}
    {% endfor %}

    {% for reply in reply_list %}
        {% if reply.parent.id == comment_id %}
        <div id="comment_aria_list_{{ reply.id }}" class="comment_aria_list">
            <a href="{% url 'myus:userpage' reply.author.nickname %}">
                <img src="{{ reply.author.user_image.url }}" title="{{ reply.author.nickname }}" class="profile_image_comment">
            </a>
            <div class="comment_aria_list_1">
                <p>{{ reply.author.nickname }}</p>
                <time>{{ reply.created|date:'Y/m/d H:i' }}</time>
            </div>
            <div id="comment_aria_list_2_{{ reply.id }}" class="comment_aria_list_2">{{ reply.text|linebreaksbr|urlize }}</div>
            {% if reply.author.id == user.id %}
                {% include 'parts/modal_content_caht_reply.html' %}
            {% endif %}
        </div>
        <div id="edit_update_main_{{ reply.id }}" class="edit_update_main_chat">
            <form method="POST" action="{% url 'myus:chat_message_update' reply.id %}" comment-id="{{ reply.id }}" class="edit_update_chat">
                {% csrf_token %}
                <a href="{% url 'myus:userpage' reply.author.nickname %}">
                    <img src="{{ reply.author.user_image.url }}" title="{{ reply.author.nickname }}" class="profile_image_comment">
                </a>
                <div class="edit_textarea_caht">
                    <textarea name="update_text" rows="1" class="textarea_br" placeholder="メッセージ入力" id="comment_form_update_{{ reply.id }}" required>{{ reply.text }}</textarea>
                    <div class="chat_frame"></div>
                    <div class="comment_input_chat"></div>
                    <div class="edit_update_footer">
                        <input type="button" name="cancel" value="キャンセル" comment-id="{{ reply.id }}" class="btn btn-light btn-xs edit_update_cancel">
                        <input type="submit" name="update" value="更新" class="btn btn-success btn-xs">
                    </div>
                </div>
            </form>
        </div>
        {% endif %}
    {% endfor %}
    <div id="reply_aria_add"></div>

    <footer class="chat_footer_thread">
        <form method="POST" action="{% url 'myus:chat_reply' %}" id="reply_form" obj-id="{{ object.id }}" comment-id="{{ comment_id }}">{% csrf_token %}
            {% if is_period %}
            <textarea name="reply" rows="1" class="textarea_br" placeholder="チャット期間が過ぎています！" disabled="disabled"></textarea>
            <div class="chat_frame chat_frame_color"></div>
            <div class="comment_input_chat">
                <button type="submit" class="btn btn-secondary btn-sm" title="送信" disabled>
                    <i class="bi bi-caret-right-fill" style="font-size: 1.2em;"></i>
                </button>
            </div>
            {% elif user.is_authenticated %}
            <textarea name="reply" rows="1" class="textarea_br" placeholder="スレッド返信" required></textarea>
            <div class="chat_frame"></div>
            <div class="comment_input_chat">
                <button type="submit" class="btn btn-primary btn-sm" title="送信">
                    <i class="bi bi-caret-right-fill" style="font-size: 1.2em;"></i>
                </button>
            </div>
            {% else %}
            <textarea name="reply" rows="1" class="textarea_br" placeholder="チャットするにはログインが必要です！" disabled="disabled"></textarea>
            <div class="chat_frame chat_frame_color"></div>
            <div class="comment_input_chat">
                <button type="submit" class="btn btn-secondary btn-sm" title="送信" disabled>
                    <i class="bi bi-caret-right-fill" style="font-size: 1.2em;"></i>
                </button>
            </div>
            {% endif %}
        </form>
    </footer>
</div>

templates/parts/comment.html
{% load static %}
{% load humanize %}

{% for comment in comment_list reversed %}
<div id="comment_aria_list_{{ comment.id }}" class="comment_aria_list">
    <a href="{% url 'myus:userpage' comment.author.nickname %}">
        <img src="{{ comment.author.user_image.url }}" title="{{ comment.author.nickname }}" class="profile_image_comment">
    </a>

    <div class="comment_aria_list_1">
        <p>{{ comment.author.nickname }}</p>
        <time>{{ comment.created|date:'Y/m/d H:i' }}</time>
    </div>

    <div id="comment_aria_list_2_{{ comment.id }}" class="comment_aria_list_2">{{ comment.text|linebreaksbr|urlize }}</div>

    <div class="comment_aria_list_3">
        {% if user.is_authenticated %}
        <form method="POST" action="{% url 'myus:like_form_comment' %}" class="like_form_aria">
            {% csrf_token %}
            {% if comment.comment_liked %}
            <button type="submit" name="comment_id" value="{{ comment.id }}" class="like_form_comment like_fill">
                <i class="bi bi-hand-thumbs-up-fill icon-font like_color_{{ comment.id }}" title="いいね"></i>
            </button>
            {% else %}
            <button type="submit" name="comment_id" value="{{ comment.id }}" class="like_form_comment like_no">
                <i class="bi bi-hand-thumbs-up icon-font like_color_{{ comment.id }}" title="いいね"></i>
            </button>
            {% endif %}
        </form>
        {% else %}
        <i class="bi bi-hand-thumbs-up icon-font rgb100" title="いいね"></i>
        {% endif %}
        <span id="like_count_{{ comment.id }}" class="like_count rgb100">{{ comment.total_like|intcomma }}</span>

        <label id="reply_button_{{ comment.id }}" comment-id="{{ comment.id }}" class="reply_button">▼ 返信</label>
        <label id="reply_button_cancel_{{ comment.id }}" comment-id="{{ comment.id }}" class="reply_button_cancel vanish">▲ 返信</label>

        <label id="reply_list_button_{{ comment.id }}" comment-id="{{ comment.id }}" class="reply_list_button">
            <span id="reply_count_{{ comment.id }}" class="reply_count">▼ スレッド {{ comment.reply_count|intcomma }} 件</span>
            <span>表示</span>
        </label>
        <label id="reply_list_button_cancel_{{ comment.id }}" comment-id="{{ comment.id }}" class="reply_list_button_cancel vanish">
            <span id="reply_count_{{ comment.id }}" class="reply_count">▲ スレッド {{ comment.reply_count|intcomma }} 件</span>
            <span>表示</span>
        </label>

        <form method="POST" action="{% url 'myus:reply_form' %}" obj-id="{{ object.id }}" comment-id="{{ comment.id }}" path="{{ request.path }}" id="comment_aria_list_reply_{{ comment.id }}" class="comment_aria_list_4 reply_form">
            {% csrf_token %}
            <div class="reply_input">
                {% if user.is_authenticated %}
                <a href="{% url 'myus:userpage' user.nickname %}">
                    <img src="{{ user.user_image.url }}" title="{{ user.nickname }}" class="profile_image_reply">
                </a>
                <textarea name="reply" rows="1" class="textarea_br" placeholder="返信コメント入力" required></textarea>
                <div class="reply_button_group">
                    <input type="button" name="cancel" value="キャンセル" comment-id="{{ comment.id }}" class="btn btn-light btn-xs reply_cancel_button">
                    <input type="submit" name="reply_form" value="コメント" class="btn btn-primary btn-xs">
                </div>
                {% else %}
                <img src="{% static 'img/user_icon.png' %}" title="匿名" class="profile_image_reply">
                <textarea name="reply" rows="1" class="textarea_br" placeholder="返信コメントするにはログインが必要です！" disabled></textarea>
                <div class="reply_button_group">
                    <input type="button" name="cancel" value="キャンセル" comment-id="{{ comment.id }}" class="btn btn-light btn-xs reply_cancel_button">
                    <input type="submit" name="reply_form" value="コメント" class="btn btn-secondary btn-xs" disabled>
                </div>
                {% endif %}
            </div>
        </form>

        <div class="comment_aria_list_space"></div>

        <div id="reply_aria_list_{{ comment.id }}" class="comment_aria_list_5">
        <div id="reply_aria_add"></div>
        {% include 'parts/reply.html' %}
        </div>
    </div>
    {% include 'parts/modal_content_comment.html' %}
</div>
<div id="edit_update_main_{{ comment.id }}" class="edit_update_main">
    <form method="POST" action="{% url 'myus:comment_update' comment.id %}" comment-id="{{ comment.id }}" class="edit_update">
        {% csrf_token %}
        <a href="{% url 'myus:userpage' comment.author.nickname %}">
            <img src="{{ comment.author.user_image.url }}" title="{{ comment.author.nickname }}" class="profile_image_comment">
        </a>
        <div class="comment_input_update">
            <textarea name="update_text" rows="1" class="textarea_br" placeholder="コメント入力" id="comment_form_update_{{ comment.id }}" required>{{ comment.text }}</textarea>
            <div class="edit_update_footer">
                <input type="button" name="cancel" value="キャンセル" comment-id="{{ comment.id }}" class="btn btn-light btn-xs edit_update_cancel">
                <input type="submit" name="update" value="更新" class="btn btn-success btn-xs">
            </div>
        </div>
    </form>
</div>
{% endfor %}

templates/parts/detail_common.html
{% load static %}
{% load humanize %}

<div class="article_detail_aria">
    <h1 title="{{ object.title }}">{{ object.title }}</h1>

    <time class="article_detail_aria_1">{{ object.created|date:'Y/m/d H:i' }}</time>

    <div class="article_detail_aria_2">
        <div class="read">
            <i class="bi bi-caret-right-square icon-font" title="閲覧数"></i>
            <span>{{ object.read|intcomma }}</span>
        </div>
        {% if user.is_authenticated %}
            <form method="POST" action="{% url 'myus:like_form' %}" path="{{ request.path }}">{% csrf_token %}
                {% if liked %}
                <button type="submit" name="videomodel_id" value="{{ object.id }}" class="like_form like_fill">
                    <i class="bi bi-hand-thumbs-up-fill icon-font like_color" title="いいね"></i>
                </button>
                {% else %}
                <button type="submit" name="videomodel_id" value="{{ object.id }}" class="like_form like_no">
                    <i class="bi bi-hand-thumbs-up icon-font like_color" title="いいね"></i>
                </button>
                {% endif %}
                <span class="like_count">{{ object.total_like|intcomma }}</span>
            </form>
        {% else %}
            <i class="bi bi-hand-thumbs-up icon-font" title="いいね"></i>
            <span>{{ object.total_like|intcomma }}</span>
        {% endif %}
    </div>

    <div class="article_detail_aria_3">
        {% include 'parts/tag.html' %}
    </div>
</div>
<hr>

<input type="checkbox" id="content_detail_check_id" class="content_detail_check">
<label for="content_detail_check_id" class="content_detail_check_label1">拡大表示</label>
<label for="content_detail_check_id" class="content_detail_check_label2">縮小表示</label>

<div class="content_detail_aria">
    <div class="content_detail">
        <a href="{% url 'myus:userpage' object.author.nickname %}">
            <img src="{{ object.author.user_image.url }}" title="{{ object.author.nickname }}" class="profile_image_detail">
        </a>
        <div class="username_space">{{ object.author.nickname }}</div>
        <div class="registered_person">登録者数
            <span class="follower_count">{{ object.author.follower_count|intcomma }}</span>
        </div>
        <p class="content_detail_p1">{{ object.content|linebreaksbr|urlize }}</p>
        <p class="content_detail_p2">{{ object.lyrics|linebreaksbr }}</p>

        <div class="content_detail_p3">
            {% if user.nickname == object.author.nickname %}
            <button class="btn btn-secondary" disabled>フォローする</button>
            {% elif user.is_authenticated %}
            <form method="POST" action="{% url 'myus:follow_create' object.author.nickname %}" class="follow_form">{% csrf_token %}
                {% if followed %}
                <button type="submit" name="following_id" value="{{ object.author.nickname }}" class="btn btn-danger follow_change">解除する</button>
                {% else %}
                <button type="submit" name="following_id" value="{{ object.author.nickname }}" class="btn btn-success follow_change">フォローする</button>
                {% endif %}
            </form>
            {% else %}
            <button class="btn btn-secondary" disabled>フォローする</button>
            {% endif %}
        </div>
    </div>
</div>
<hr>

<form method="POST" action="{% url 'myus:comment_form' %}" id="comment_form" obj-id="{{ object.id }}" path="{{ request.path }}">{% csrf_token %}
    <div class="comment_input">
        <p>コメント総数
            <span id="comment_count">{{ object.comment_count|intcomma }}</span>
        </p>
        {% if user.is_authenticated %}
        <a href="{% url 'myus:userpage' user.nickname %}">
            <img src="{{ user.user_image.url }}" title="{{ user.nickname }}" class="profile_image_comment">
        </a>
        <textarea name="text" rows="1" class="textarea_br" placeholder="コメント入力" required></textarea>
        <input type="submit" name="text" value="コメント" class="btn btn-primary btn-sm">
        {% else %}
        <img src="{% static 'img/user_icon.png' %}" title="匿名" class="profile_image_comment">
        <textarea name="text" rows="1" class="textarea_br" placeholder="コメントするにはログインが必要です！" disabled></textarea>
        <input type="submit" name="text" value="コメント" class="btn btn-secondary btn-sm" disabled>
        {% endif %}
    </div>
</form>

<input type="checkbox" id="comment_aria_check_id" class="comment_aria_check">
<label for="comment_aria_check_id" class="comment_aria_check_label1">拡大表示</label>
<label for="comment_aria_check_id" class="comment_aria_check_label2">縮小表示</label>

<div class="comment_aria">
    <div id="comment_aria_add"></div>

    {% include 'parts/comment.html' %}
</div>

<hr class="comment_aria_hr">

<div class="advertise_aria">
    <h2>広告表示</h2>
    {% include 'parts/article_advertise_auto.html' %}
</div>

templates/parts/reply.html
{% load humanize %}

{% for reply in reply_list reversed %}
    {% if reply.parent.id == comment.id %}
    <div id="comment_aria_list_{{ reply.id }}" class="reply_aria_list">
        <a href="{% url 'myus:userpage' reply.author.nickname %}">
            <img src="{{ reply.author.user_image.url }}" title="{{ reply.author.nickname }}" class="profile_image_reply">
        </a>

        <div class="reply_aria_list_1">
            <p>{{ reply.author.nickname }}</p>
            <time>{{ reply.created|date:'Y/m/d H:i' }}</time>
        </div>

        <div id="comment_aria_list_2_{{ reply.id }}" class="reply_aria_list_2">{{ reply.text|linebreaksbr|urlize }}</div>

        <div class="reply_aria_list_3">{{ reply.comment_liked }}
            {% if user.is_authenticated %}
            <form method="POST" action="{% url 'myus:like_form_comment' %}" class="like_form_aria">{% csrf_token %}
                {% if reply.comment_liked %}
                <button type="submit" name="comment_id" value="{{ reply.id }}" class="like_form_comment like_fill">
                    <i class="bi bi-hand-thumbs-up-fill icon-font like_color_{{ reply.id }}" title="いいね"></i>
                </button>
                {% else %}
                <button type="submit" name="comment_id" value="{{ reply.id }}" class="like_form_comment like_no">
                    <i class="bi bi-hand-thumbs-up icon-font like_color_{{ reply.id }}" title="いいね"></i>
                </button>
                {% endif %}
            </form>
            {% else %}
            <i class="bi bi-hand-thumbs-up icon-font rgb100" title="いいね"></i>
            {% endif %}
            <span id="like_count_{{ reply.id }}" class="like_count rgb100">{{ reply.total_like|intcomma }}</span>
        </div>
        {% include 'parts/modal_content_reply.html' %}
    </div>
    <div id="edit_update_main_{{ reply.id }}" class="edit_update_main">
        <form method="POST" action="{% url 'myus:comment_update' reply.id %}" comment-id="{{ reply.id }}" class="edit_update">
            {% csrf_token %}
            <a href="{% url 'myus:userpage' reply.author.nickname %}">
                <img src="{{ reply.author.user_image.url }}" title="{{ reply.author.nickname }}" class="profile_image_reply">
            </a>
            <div class="comment_input_update">
                <textarea name="update_text" rows="1" class="textarea_br" placeholder="コメント入力" id="comment_form_update_{{ reply.id }}" required>{{ reply.text }}</textarea>
                <div class="edit_update_footer">
                    <input type="button" name="cancel" value="キャンセル" comment-id="{{ reply.id }}" class="btn btn-light btn-xs edit_update_cancel">
                    <input type="submit" name="update" value="更新" class="btn btn-success btn-xs">
                </div>
            </div>
        </form>
    </div>
    {% endif %}
{% endfor %}